# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/PSU/Winter_2024/544/P2/ClosedLoopPID-MicroBlazeAXI-FreeRTOS/Robert/Proj2_rel/booleanfpga.xdc

# Block Designs: bd/embsys/embsys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys || ORIG_REF_NAME==embsys} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_0/embsys_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_0 || ORIG_REF_NAME==embsys_microblaze_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_dlmb_v10_0/embsys_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_dlmb_v10_0 || ORIG_REF_NAME==embsys_dlmb_v10_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_ilmb_v10_0/embsys_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_ilmb_v10_0 || ORIG_REF_NAME==embsys_ilmb_v10_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_dlmb_bram_if_cntlr_0/embsys_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==embsys_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_ilmb_bram_if_cntlr_0/embsys_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==embsys_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_lmb_bram_0/embsys_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_lmb_bram_0 || ORIG_REF_NAME==embsys_lmb_bram_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_xbar_0/embsys_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_xbar_0 || ORIG_REF_NAME==embsys_xbar_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_axi_periph_0/embsys_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_periph_0 || ORIG_REF_NAME==embsys_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_intc_0 || ORIG_REF_NAME==embsys_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_xlconcat_0/embsys_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_xlconcat_0 || ORIG_REF_NAME==embsys_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_mdm_1_0/embsys_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_mdm_1_0 || ORIG_REF_NAME==embsys_mdm_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_clk_wiz_1_0/embsys_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_clk_wiz_1_0 || ORIG_REF_NAME==embsys_clk_wiz_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_rst_clk_wiz_1_100M_0/embsys_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==embsys_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_timer_0_0 || ORIG_REF_NAME==embsys_axi_timer_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_uartlite_0_0/embsys_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_uartlite_0_0 || ORIG_REF_NAME==embsys_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_iic_0_0/embsys_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_iic_0_0 || ORIG_REF_NAME==embsys_axi_iic_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_nexys4io_0_0/embsys_nexys4io_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_nexys4io_0_0 || ORIG_REF_NAME==embsys_nexys4io_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_bidirec_0_0/embsys_bidirec_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_bidirec_0_0 || ORIG_REF_NAME==embsys_bidirec_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_bidirec_1_0/embsys_bidirec_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_bidirec_1_0 || ORIG_REF_NAME==embsys_bidirec_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_pc_0/embsys_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_auto_pc_0 || ORIG_REF_NAME==embsys_auto_pc_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_pc_1/embsys_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_auto_pc_1 || ORIG_REF_NAME==embsys_auto_pc_1} -quiet] -quiet

# XDC: d:/PSU/Winter_2024/544/P2/ClosedLoopPID-MicroBlazeAXI-FreeRTOS/Robert/project_2/project_2.gen/sources_1/bd/embsys/embsys_ooc.xdc
